openapi: 3.0.1
info:
  title: My API
  version: 1.0.0
paths:
  /pets:
    get:
      operationId: getPets
      responses:
        '200':
          $ref: '#/components/responses/ListPetsRes'
    post:
      operationId: createPet
      requestBody:
        description: Pet object to create
        content:
          application/json: {}
      responses:
        '201':
          $ref: '#/components/responses/PetRes'
  '/pets/{id}':
    get:
      operationId: getPetById
      responses:
        '200':
          $ref: '#/components/responses/PetRes'
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
components:
  responses:
    ListPetsRes:
      description: ok
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  minimum: 1
                name:
                  type: string
                  example: Odie
    PetRes:
      description: ok
      content:
        application/json:
          examples:
            garfield:
              value:
                id: 1
                name: Garfield
